
CREATE DATABASE course_planner_db;

USE course_planner_db;

CREATE TABLE IF NOT EXISTS courses (
	id INTEGER(10) AUTO_INCREMENT,
	course_name VARCHAR(100) NOT NULL,
	planned BOOLEAN NOT NULL DEFAULT true,
	current BOOLEAN NOT NULL DEFAULT false,
	completed BOOLEAN NOT NULL DEFAULT false,
	semester INTEGER(5) NOT NULL DEFAULT 20172,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS plans (
	id INTEGER(10) AUTO_INCREMENT,
	plan_name VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);
